### ISSUE TITLE
How exactly to do this?

### ISSUE THREAD

**Issue by Lord-Memester** [Archef2000/homeassistant-upsplus#1]
> Use the ssh addon to edit the /boot/config.txt file and add dtparam=i2c_arm=on and dtparam=i2c_vc=on

I am not sure how to do this. Also, which SSH addon?

**Comment by archef2000** [comment]
What type of instalation do you have

**Comment by Lord-Memester** [comment]
> What type of instalation do you have

the Homr assistant OS

**Comment by archef2000** [comment]
So you have an addon page where you can search after SSH install it and make sure the switch PRIVILEGED is on then you need to type 
```shell
ls /dev/*-i2c
``` 
If nothing is listed you need to enable i2c

**Comment by Lord-Memester** [comment]
it is listed, but i didn't see anything different. nothing new or useful about the Pi appeared

**Comment by archef2000** [comment]
Where do you not see anything different

**Comment by Lord-Memester** [comment]
nevermind, i forgot to configure it in the integrations
