### ISSUE TITLE
Home Assistant OS Instructions Update for I2C setup

### ISSUE THREAD

**Issue by Robrowski** [Archef2000/homeassistant-upsplus#2]
Hello! I have to start by saying thank you for developing this; it works great and I got there in the end!

Setup was rough for me with HA-OS until I stumbled through https://community.home-assistant.io/t/add-on-hassos-i2c-configurator/264167/2 and eventually got to https://www.home-assistant.io/common-tasks/os#enable-i2c, the missing step was adding `/CONFIG/modules/rpi-i2c.conf`. Maybe consider simplifying your README and the error log to just point to the HA docs? https://www.home-assistant.io/common-tasks/os#enable-i2c

**Comment by archef2000** [comment]
I will have a look

**Comment by archef2000** [comment]
Because i don't have HA-OS setup what error do you mean ?

**Comment by Robrowski** [comment]
I was getting this error https://github.com/archef2000/homeassistant-upsplus/blob/main/custom_components/upsplus/translations/en.json#L5C26-L5C26

**Comment by archef2000** [comment]
Ok i will add a link to HA docs in the error. In the docs it already says to create `/CONFIG/modules/rpi-i2c.conf` so i don't need to add that too?

**Comment by Robrowski** [comment]
Yeah I agree, a reminder to go to the HA docs is good 👍

**Comment by archef2000** [comment]
I have added it in the `v1.0.2` release.
