### ISSUE TITLE
Does not show any information on a HA docker 

### ISSUE THREAD

**Issue by luizrrocha** [Archef2000/homeassistant-upsplus#4]
Hello, can you put a screen with what it is supposed to show ? Mine shows only that the version is up-to-date, no UPS info at all. I use a Raspi 4b with HA docker version and have no idea on how to "mount the /dev/i2c-1 device to the image"...

Regards,

Luiz

**Comment by archef2000** [comment]
How do you run the conatiner? With `docker run`, `docker compose`, etc

**Comment by luizrrocha** [comment]
Hi, it runs via systemd on the Pi boot.

**Comment by archef2000** [comment]
Ok but how do you update the container for example.

**Comment by luizrrocha** [comment]
Homeassistant Settings dashboard option updates and restarts the container.
Recently was updated to 2023.10.5:

db4846b37835
ghcr.io/home-assistant/raspberrypi4-64-homeassistant:2023.10.5   "/init"
               3 days ago       Up 26 minutes

                       homeassistant

**Comment by archef2000** [comment]
Ok what version are you running again?

**Comment by luizrrocha** [comment]
***@***.***:/etc/systemd/system# docker -v
Docker version 24.0.6, build ed223bc

***@***.***:/etc/systemd/system# uname -a
Linux Pi4Central 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023
aarch64 GNU/Linux

Home Assistant 2023.10.5
Supervisor 2023.10.1
Frontend 20231005.0 - latest

52PI UPS Integration update
31 minutes ago
Last changed:31 minutes ago

Last updated:31 minutes ago
Up-to-date
Installed version v1.1.0

**Comment by archef2000** [comment]
Ok go into you HA UI into Settings -> About and make a Picture of that for me please.

**Comment by luizrrocha** [comment]
Here it is:

[image: image.png]

**Comment by archef2000** [comment]
You need to upload it via the UI on Github and not EMail

**Comment by luizrrocha** [comment]
<img width="454" alt="image" src="https://github.com/archef2000/homeassistant-upsplus/assets/8258864/8bcc3853-77a1-487a-b906-5db29fd86352">

**Comment by archef2000** [comment]
Ok so you run the HA Supervised version do you have the `sudo raspi-config` command available on the host?

**Comment by luizrrocha** [comment]
Yes, and I enabled the I2C port and can read UPS information on the PI
command line:

***@***.***:/tmp# cat upsPlus.log
------------------------------------------------------------
------Current information of the detected Raspberry Pi------
------------------------------------------------------------
Raspberry Pi Supply Voltage: 5.012 V
Raspberry Pi Current Current Consumption: 1915.728 mA
Raspberry Pi Current Power Consumption: 9591.253 mW
------------------------------------------------------------
-------------------Batteries information-------------------
------------------------------------------------------------
Voltage of Batteries: 4.200 V
Battery Current (Charging) Rate: 166.098 mA
Current Battery Power Supplement: 790.244 mW
Successfully set the protection voltage to: 3700 mV
------------------------------------------------------------
Currently charging via Type C Port.
***@***.***:/tmp#



/usr/sbin/i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- 17 -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- 45 -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

**Comment by archef2000** [comment]
Ok do you have HACS installed?

**Comment by luizrrocha** [comment]
Yes, HACS is installed. I used it to install your package.

**Comment by archef2000** [comment]
Have you setup my Integration?

**Comment by luizrrocha** [comment]
I assume so, as it shows like this:
<img width="451" alt="image" src="https://github.com/archef2000/homeassistant-upsplus/assets/8258864/089ff2da-c7d3-4cf7-aa1e-197e1f05ca55">

**Comment by archef2000** [comment]
No i mean under: [![Open your Home Assistant instance and show your integrations.](https://my.home-assistant.io/badges/integrations.svg)](https://my.home-assistant.io/redirect/integrations/)

**Comment by luizrrocha** [comment]
It shows as a service of HACS, not as a separate integration. It is listed as a device under HACS:
<img width="1694" alt="image" src="https://github.com/archef2000/homeassistant-upsplus/assets/8258864/c9ca92fe-249d-4367-99bd-0721e4e9b491">

**Comment by archef2000** [comment]
OK you need to clear the cache of your browser.

**Comment by luizrrocha** [comment]
Hi, I did clear the cache, restarted the Raspi, removed and reinstalled your integration and the situation did not change from above...

**Comment by archef2000** [comment]
So you can't add the Integration in the menu above?

**Comment by luizrrocha** [comment]
No, it only shows on the devices/services list of HACS

**Comment by archef2000** [comment]
Do you see errors inside of HA

**Comment by luizrrocha** [comment]
No, no errors.

**Comment by archef2000** [comment]
Sorry for the question but have you in this order:
* installed the integration via HACS
* restarted HA completly
* SHIFT refreshed the integartions page
* clicked the + button
* searched after "UPS I2C"

**Comment by luizrrocha** [comment]
Oh, the last step was not done ! I did not know that from the Github. Now I performed the initial config and it is showing all data. 

Thank you!

**Comment by archef2000** [comment]
How many sensors do you have and do you see amy errors?

**Comment by luizrrocha** [comment]
UPS, just one. Sensors in general, close to 50, No errors are reported.

**Comment by archef2000** [comment]
Good im closing this issue, but feel free to ask any questions you have left.
