### ISSUE TITLE
Configure Connection issues

### ISSUE THREAD

**Issue by FMetzl** [Archef2000/homeassistant-upsplus#6]
I cant Configgure the device, no entitis showing up i2c is configured.

![Screenshot 2024-09-25 183644](https://github.com/user-attachments/assets/8b5c504f-c802-41bb-93e2-c6916890ab00)

**Comment by archef2000** [comment]
what do you see in the HA logs?

**Comment by FMetzl** [comment]
It logs an error Already while setting up. One each for sensor, buutton and switch.

This is the description for the Button:

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:361
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 20:11:29 (1 Vorkommnisse)
Zuletzt protokolliert: 20:11:29

Error while setting up upsplus platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/upsplus/sensor.py", line 114, in async_setup_entry
    sensors.append(SerialNumber(config))
                   ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/upsplus/sensor.py", line 87, in __init__
    self._manager = UPSManager()
                    ^^^^^^^^^^^^
  File "/config/custom_components/upsplus/battery.py", line 23, in __init__
    self.sw_version = read_buff(self.bus,40,41)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/upsplus/battery.py", line 31, in read_buff
    result = bus.read_byte_data(DEVICE_ADDR, index1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/smbus2/smbus2.py", line 433, in read_byte_data
    ioctl(self.fd, I2C_SMBUS, msg)
OSError: [Errno 121] Remote I/O error

The rest locks similar

**Comment by archef2000** [comment]
Did you enable the i2c bus?
What install type are you using for HA?

**Comment by FMetzl** [comment]
I enabled it with the I2C configurator. https://community.home-assistant.io/t/add-on-hassos-i2c-configurator/264167

I use the Home assistant OS version

**Comment by archef2000** [comment]
Could you please run `lsmod | grep i2c` on the host.

**Comment by FMetzl** [comment]
Console answer


![Screenshot 2024-09-25 ](https://github.com/user-attachments/assets/abea7200-b288-4cc5-84d8-acf0dda075e9)

**Comment by archef2000** [comment]
Could you try reading from the device with:
```sh
i2cget -y 1 0x17 0x16
i2cget -y 1 0x17 0x17
i2cget -y 1 0x17 0x18
```

**Comment by FMetzl** [comment]
It dosent find the i2cget command.

**Comment by archef2000** [comment]
Install it with: sudo apt install i2c-tools

**Comment by FMetzl** [comment]
Hass Os hass no sudo or apt maybe i need to reinstall the system this one was transfered froom a 64 bit VM

**Comment by archef2000** [comment]
apk add i2c-tools

And have you rebooted the machine after setting up i2c?

**Comment by FMetzl** [comment]
it spits oout error Could not open file "//dev/i2c-1" : Operation not Permited

**Comment by FMetzl** [comment]
I reebooted Multiple Times, whilee troubleshooting over 20 times

**Comment by FMetzl** [comment]
Im Very Sorry, Today i foud Out my Device was in OTA Mode, after finishing Updating the Frimare it worked without Prooblems

**Comment by archef2000** [comment]
Giod to hear as I was running put if options.
